#!/usr/bin/bash

cat /mnt/e/logfiles/observations/logfile.191212 | grep "object" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191212 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191213 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191214 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191215 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191216 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191217 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191218 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191219 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191220 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191221 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191222 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191223 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191224 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191225 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191226 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191227 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191228 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191229 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191230 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191231 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200101 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200103 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200104 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200105 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200106 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200107 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200108 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200109 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200110 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200111 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200112 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200113 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200114 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200115 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200116 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200117 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200118 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200119 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200120 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200121 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200122 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200123 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200124 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200125 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200126 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200127 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200128 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200129 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200130 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200131 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200201 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200202 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200203 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200204 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200205 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200206 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200207 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200208 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200209 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200210 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200211 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200213 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200214 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200215 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200216 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200217 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200218 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200219 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200220 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200221 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200222 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200223 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200224 | grep "2998" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
