#!/usr/bin/bash

rm /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190813 | grep "object" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190813 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190814 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190815 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190816 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190817 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190818 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190821 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190822 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190823 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190824 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190825 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190826 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190828 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190830 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190831 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190902 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190903 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190904 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190905 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190906 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190907 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190908 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190909 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190910 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190911 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190912 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190913 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190914 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190915 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190916 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190917 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190918 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190919 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190920 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190921 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190922 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190923 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190924 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190925 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190926 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190927 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190928 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190929 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190930 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191001 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191002 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191003 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191004 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191005 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191006 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191007 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191008 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191009 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191010 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191011 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191012 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191013 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191014 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191015 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191016 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191017 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191018 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191019 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191020 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191021 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191022 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191023 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191025 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191026 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191029 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191030 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191031 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191101 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191102 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191103 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191104 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191105 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191107 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191108 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191109 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191110 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191111 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191112 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191113 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191115 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191116 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191117 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191118 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191119 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191120 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191121 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191122 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191123 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191124 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191125 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191126 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191127 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191128 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191129 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191130 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191201 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191202 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191203 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191204 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191205 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191206 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191207 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191208 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191212 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191213 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191214 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191215 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191216 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191217 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191218 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191219 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191220 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191221 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191222 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191223 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191224 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191225 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191226 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191227 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191228 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191229 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191230 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191231 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200101 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200103 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200104 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200105 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200106 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200107 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200108 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200109 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200110 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200111 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200112 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200113 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200114 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200115 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200116 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200117 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200118 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200119 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200120 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200121 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200122 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200123 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200124 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200125 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200126 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200127 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200128 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200129 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200130 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200131 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200201 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200202 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200203 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200204 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200205 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200206 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200207 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200208 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200209 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200210 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200211 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200213 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200214 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200215 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200216 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200217 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200218 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200219 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200220 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200221 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200222 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200223 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200224 | grep "2894" >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
