#!/usr/bin/bash

rm /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190813 | awk '{if($24=="object|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190813 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190814 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190815 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190816 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190817 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190818 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190821 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190822 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190823 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190824 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190825 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190826 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190828 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190830 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190831 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190902 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190903 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190904 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190905 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190906 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190907 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190908 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190909 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190910 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190911 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190912 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190913 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190914 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190915 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190916 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190917 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190918 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190919 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190920 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190921 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190922 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190923 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190924 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190925 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190926 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190927 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190928 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190929 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.190930 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191001 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191002 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191003 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191004 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191005 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191006 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191007 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191008 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191009 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191010 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191011 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191012 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191013 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191014 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191015 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191016 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191017 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191018 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191019 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191020 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191021 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191022 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191023 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191025 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191026 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191029 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191030 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191031 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191101 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191102 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191103 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191104 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191105 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191107 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191108 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191109 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191110 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191111 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191112 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191113 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191115 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191116 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191117 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191118 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191119 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191120 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191121 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191122 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191123 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191124 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191125 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191126 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191127 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191128 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191129 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191130 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191201 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191202 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191203 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191204 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191205 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191206 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191207 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191208 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191212 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191213 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191214 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191215 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191216 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191217 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191218 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191219 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191220 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191221 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191222 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191223 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191224 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191225 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191226 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191227 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191228 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191229 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191230 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.191231 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200101 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200103 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200104 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200105 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200106 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200107 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200108 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200109 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200110 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200111 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200112 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200113 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200114 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200115 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200116 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200117 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200118 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200119 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200120 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200121 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200122 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200123 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200124 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200125 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200126 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200127 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200128 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200129 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200130 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200131 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200201 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200202 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200203 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200204 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200205 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200206 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200207 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200208 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200209 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200210 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200211 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200213 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200214 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200215 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200216 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200217 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200218 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200219 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200220 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200221 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200222 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200223 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200224 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200225 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
cat /mnt/e/logfiles/observations/logfile.200226 | awk '{if($24=="2894|"){print $0}}' >> /mnt/e/IRAF/iraf-reductions-FOCES/fxcor/output/grep_redID_out.txt
